name: Update rain.json

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch Aozora
        run: |
          mkdir aozora
          cd aozora
          curl -L https://www.aozora.gr.jp/cards/000081/files/456_ruby_145.zip -o text.zip
          unzip -o text.zip

      - name: Run Python
        run: python scripts/update.py

      - name: Commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "update rain quote" || echo "no changes"
          git push
